# Generated by Django 4.2.9 on 2024-05-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequests',
            name='cleaner',
            field=models.ForeignKey(limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
