# Generated by Django 4.2.5 on 2024-03-08 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_cleaningschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningschedule',
            name='schedule_type',
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='Task',
            field=models.CharField(blank=True, choices=[('vacuuming', 'vacuuming'), ('mopping', 'mopping'), ('dusting', 'dusting'), ('sanitizing', 'sanitizing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningschedule',
            name='area_building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningschedule',
            name='assigned_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cleaningschedule',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
