# Generated by Django 4.2.9 on 2024-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0003_alter_cleaningrequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequests',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
