# Generated by Django 4.2.5 on 2024-03-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0003_remove_cleaningschedule_schedule_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='cleaningschedule',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='cleaningschedule',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='cleaningschedule',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cleaningschedule',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='completed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='task',
            field=models.CharField(blank=True, choices=[('vacuuming', 'Vacuuming'), ('mopping', 'Mopping'), ('dusting', 'Dusting'), ('sanitizing', 'Sanitizing')], max_length=20, null=True),
        ),
    ]
