# Generated by Django 4.2.5 on 2024-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0004_alter_cleaningschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'supervisor'), (3, 'cleners')]),
        ),
    ]
