# Generated by Django 4.2.5 on 2024-03-13 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningschedule',
            name='assigned_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
